capabilities:
  chrome:
    os: Windows
    os_version: 10
    browser: chrome
    browser_version: latest
  safari:
    os : OS X
    os_version : Monterey
    browser : Safari
    browser_version : latest
  edge:
    os : Windows
    os_version : 11
    browser : Edge
    browser_version : latest
  firefox:
    os : OS X
    os_version : Big Sur
    browser : Firefox
    browser_version : latest